--DDL HEALTH CLINIC

-- CRIAR BASE DE DADOS 

CREATE DATABASE Health_Clinic

USE Health_Clinic

--CRIAR TABELAS 

CREATE TABLE TipoUsuario
(
	IdTipo INT PRIMARY KEY IDENTITY ,
	TipoUsuario VARCHAR (70) NOT NULL UNIQUE
)


CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (100) NOT NULL,
	Endereco VARCHAR (100) NOT NULL,
	Abertura VARCHAR  (100) NOT NULL UNIQUE ,
	Fechamento VARCHAR (100) NOT NULL,
	CNPJ VARCHAR (50) NOT NULL UNIQUE,
	RazaoSocial VARCHAR(100) NOT NULL 
)

CREATE TABLE Especialidade 
(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	Especialidade VARCHAR (50) NOT NULL
)


CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipo INT FOREIGN KEY REFERENCES TipoUsuario(IdTipo) NOT NULL,
	Email VARCHAR (50) NOT NULL UNIQUE ,
	SENHA VARCHAR (50) NOT NULL UNIQUE 
)

ALTER TABLE Usuario
ADD Nome VARCHAR (50) NOT NULL UNIQUE 

CREATE TABLE Medico 
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica (Idclinica) NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade (IdEspecialidade) NOT NULL,
	--Nome VARCHAR (50) NOT NULL, RETIRADO 
	CRM VARCHAR (50) NOT NULL UNIQUE 
)

ALTER TABLE Medico
DROP COLUMN Nome 

CREATE TABLE Paciente 
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario),
	RG VARCHAR (20) NOT NULL UNIQUE ,
	CPF VARCHAR (20) NOT NULL UNIQUE ,
	DataNascimento VARCHAR (30) NOT NULL ,
	Telefone VARCHAR (20) NOT NULL,
	Endereco VARCHAR (50) NOT NULL
)

CREATE TABLE Comentario
(
	IdComentario INT PRIMARY KEY IDENTITY,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente (IdPaciente),
	Comentario VARCHAR (100) NOT NULL
)
	
CREATE TABLE Consulta 
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREign KEY REFERENCES Medico (IdMedico),
	IdPaciente INT FOREIGN KEY REFERENCES Paciente (IdPaciente),
	IdComentario INT FOREIGN KEY REFERENCES Comentario (IdComentario),
	[Data] DATE NOT NULL,
	Hora TIME NOT NULL,
	Prontuario VARCHAR (100) NOT NULL 
)
